<?php
$NROWS = 6;
$NRCOLS = 3;

// table arrays 
$firstNames = array("Jake", "Michael", "Mikayle", "Candida", "Sofi", "Juli");
$lastNames = array("Jackson", "Julian", "Despaigne", "Gonzalez", "Gie", "Samsa");
$ages = array("15", "58", "67", "16", "27", "66");
$headers = array("First Name", "Last Name", "Age"); 

// generating rows using midterm for inspiration 
function addRows() {
    global $NROWS, $firstNames, $lastNames, $ages;
    for ($i = 0; $i < $NROWS; $i++) { 
        addSingleRow($firstNames[$i], $lastNames[$i], $ages[$i]);
    }
}


function addSingleRow($fname, $lname, $age) {
    echo "<tr><td>" . $fname . "</td><td>" . $lname . "</td><td>" . $age . "</td></tr>";
}

// generates the columns as well 
function addCols() {
    global $NRCOLS, $headers;
    echo "<tr>"; 
    for ($i = 0; $i < $NRCOLS; $i++) {
        addHeaderCols($headers[$i]);
    }
    echo "</tr>"; 
}

// Print a single column header
function addHeaderCols($tHead) {
    echo '<th style="width:75%;">' . $tHead . '</th>';  
}
?>

<html>
<head>
    <title>PHP Table</title>
    <style>
        tr:nth-child(even) {
            background-color: plum;
        }
    </style>
</head>
<body>

<h1 style="color:plum;">Tables Generated by PHP</h1>

<table id="table"> 
  <?php addCols(); ?>  
  <?php addRows(); ?>  
</table>

</body>
</html>
